#!/bin/bash

ansible_install_linux() {
  if type apt > /dev/null 2>&1; then
    if [ $(apt list 2> /dev/null | awk -F/ '$1 == "ansible" {print 0}') -ne 0 ]; then
      sudo add-apt-repository universe \
      && sudo apt install -y ansible python3-apt
    fi
  elif type yum > /dev/null 2>&1; then
    if !yum list installed ansible > /dev/null 2>&1; then
      sudo yum install -y ansible
    fi
  elif type dnf > /dev/null 2>&1; then
    if [ $(dnf list installed | awk F. '$1 == "ansible" {print 0}') -ne 0 ]; then
      sudo dnf -y install ansible
    fi
  elif type pacman > /dev/null 2>&1; then
    if pacman -Qi ansible > /dev/null 2>&1; then
      sudo pacman -S --noconfirm ansible
    fi
  fi
}

ansible_install_mac() {
  return
}

ansible_install_win() {
  return
}

OS_TYPE=$(uname)
case $OS_TYPE in
  Linux)
    ansible_install_linux
    ;;
  Darwin)
    ansible_install_mac
    ;;
  WindowsNT)
    ansible_install_win
    ;;
esac

# execute playbook
env ANSIBLE_FORCE_COLOR=true \
ansible-playbook \
  $HOME/.config/yadm/setup.yml
