-- [nvim-treesitter/nvim-treesitter] enable modules
require('nvim-treesitter.configs').setup {
  ensure_installed = {
    'awk',
    'bash',
    'dockerfile',
    'fish',
    'git_config',
    'git_rebase',
    'gitattributes',
    'gitcommit',
    'gitignore',
    'go',
    'gomod',
    'gosum',
    'hcl',
    'html',
    'htmldjango',
    'ini',
    'javascript',
    'jq',
    'json',
    'json5',
    'lua',
    'make',
    'markdown',
    'markdown_inline',
    'python',
    'regex',
    'ruby',
    'rust',
    'scss',
    'sql',
    'terraform',
    'toml',
    'vim',
    'yaml',
  },
  highlight = { enable = true },
  indent = { enable = false },
}
